programming_projects/CS50w/Project 1/wiki/encyclopedia/urls.py
from django.urls import path
import random
from . import views
from . import util
app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:page_name>/", views.display_page, name="page"),
    path("encyclopedia/search/", views.handle_search, name="search"),
    path("encyclopedia/random/", views.randomize, name="random"), 
    path("encyclopedia/new", views.new, name="new")
]

programming_projects/CS50w/Project 1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

programming_projects/CS50w/Project 1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

programming_projects/CS50w/Project 1/wiki/encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from . import util
from django.http import HttpResponse
import re
import random

def index(request):
    if request.method == "POST":
        x = request.POST["title"]
        if request.POST["edit"] == "true":
            util.save_entry(x, request.POST["content"])
        elif x not in util.list_entries() and request.POST["edit"] == "false":
            util.save_entry(x, request.POST["content"])
        else:
            return HttpResponse("ERROR! Page already exists!")
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def display_page(request, page_name):
    def cvt():
        if (obj:=util.get_entry(page_name)) == None: 
            return None
        return Markdown().convert(obj)
    return render(request, "encyclopedia/page.html", {"page":cvt(), "page_name":page_name})

def handle_search(request):
    search_result = request.POST['q']
    get_page = util.get_entry(search_result)
    if get_page == None:
        return render(request, "encyclopedia/refer.html", {"possible_entries":[x for x in util.list_entries() if search_result in x.lower()]})
        #return HttpResponse(f"NOT FOUND!\nVisit: {[x for x in util.list_entries() if search_result in x.lower()]}")
    else:
        return display_page(request, search_result)
    # return render(request, "") 

def randomize(request):
    return display_page(request, random.choice(util.list_entries()))

def new(request):
    if request.method == "POST":
        return render(request, "encyclopedia/new.html", {
            "title":request.POST["title"],
            "content":request.POST["content"],
            "edit":"true"
        })
    return render(request, "encyclopedia/new.html", {"edit":"false"})




    
    

programming_projects/CS50w/Project 1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' page_name=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

programming_projects/CS50w/Project 1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search'%}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url "encyclopedia:new" %}">Create New Page</a>
                </div>
                <div>
                    <a href="encyclopedia/random">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

programming_projects/CS50w/Project 1/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
  <form action="{% url "encyclopedia:index" %}" method="post">
    {% csrf_token %}
    <label for="title-bar" required>Title: </label> <input id="title-bar" name="title" value={{ title }}>
    <br>
    <label for="content-area">Content: </label>
    <br>
    <textarea id="content-area" name="content" value="{{ content }}">
    </textarea>
    <br>
    <input type="hidden" name="edit" value="{{ edit }}">
    <input type="submit" class="btn">
  </form>
{% endblock%}

programming_projects/CS50w/Project 1/wiki/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
{{ page_name }}
{% endblock %}
{% block body%}
    {% if page == None %}
      <h2>PAGE NOT FOUND!</h2>
    {% else %}
      {{ page | safe}}
    {% endif %}
    <footer>
      <form action="{% url "encyclopedia:new" %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ page_name }}">
        <input type="hidden" name="content" value="{{ page }}">
        <input type="hidden" name="edit" value="true">
        <input type="submit">
      </form>
    </footer>
{% endblock %}

programming_projects/CS50w/Project 1/wiki/encyclopedia/templates/encyclopedia/refer.html
{% extends "encyclopedia/layout.html" %}

{% block body%}
  <ul>
    {% for entry in possible_entries %}
      <li><a href="{% url "encyclopedia:page" page_name=entry%}">{{ entry }}</a></li> 
    {% endfor %}
  </ul>
{% endblock%}